---
title: "Building a complex query with SQL"
author: "Hector Corrada Bravo"
date: "2/15/2018"
output: html_document
---

```{r}
dbfile <- "/Users/hcorrada/Teaching/CMSC320_Spring2018/materials/lecture-notes/data/lahman2016.sqlite"
db <- DBI::dbConnect(RSQLite::SQLite(), dbfile)
```

We build the query step by step (starting at the bottom...)

- Final query: Ten players from PR _not_ in HOF with the most career hits.

```{sql, connection=db}
select m.playerID, sum(b.H) as total_hits, nameFirst, nameLast
from Master as m
  left join (select distinct playerID
      from HallOfFame
      where inducted = "Y") as hof
    on m.playerID = hof.playerID
  join Batting as b
    on m.playerID = b.playerID
where birthCountry = "P.R."
  and hof.playerID is NULL
group by m.playerID
order by total_hits desc
limit 10
```

- Total number of career hits for players from PR _not_ in HOF

```{sql, connection=db}
select m.playerID, sum(b.H) as total_hits, nameFirst, nameLast
from Master as m
  left join (select distinct playerID
      from HallOfFame
      where inducted = "Y") as hof
    on m.playerID = hof.playerID
  join Batting as b
    on m.playerID = b.playerID
where birthCountry = "P.R."
  and hof.playerID is NULL
group by m.playerID
```

- Add hits per season to table of players from PR _not_in HOF

```{sql, connection=db}
select m.playerID, b.H, nameFirst, nameLast
from Master as m
  left join (select distinct playerID
      from HallOfFame
      where inducted = "Y") as hof
    on m.playerID = hof.playerID
  join Batting as b
    on m.playerID = b.playerID
where birthCountry = "P.R."
  and hof.playerID is NULL
```

- Players from PR _not_ in HOF

```{sql, connection=db}
select m.playerID, nameFirst, nameLast
from Master as m
  left join (select distinct playerID
      from HallOfFame
      where inducted = "Y") as hof
    on m.playerID = hof.playerID
where birthCountry = "P.R."
  and hof.playerID is NULL
```

- Players in the HOF

```{sql, connection=db}
select distinct playerID
from HallOfFame
where inducted = "Y"
```

- Players from PR

```{sql, connection=db}
select playerID, nameFirst, nameLast
from Master
where birthCountry = "P.R."
```

```{r}
DBI::dbDisconnect(db)
```