<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Lecture Notes: Introduction to Data Science</title>
  <meta name="description" content="Lecture Notes: Introduction to Data Science">
  <meta name="generator" content="bookdown 0.5 and GitBook 2.6.7">

  <meta property="og:title" content="Lecture Notes: Introduction to Data Science" />
  <meta property="og:type" content="book" />
  
  
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Lecture Notes: Introduction to Data Science" />
  
  
  

<meta name="author" content="Héctor Corrada Bravo">


<meta name="date" content="2018-01-21">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="capstone-project-1.html">
<link rel="next" href="text-analysis.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Preamble</a></li>
<li class="chapter" data-level="2" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html"><i class="fa fa-check"></i><b>2</b> Introduction and Overview</a><ul>
<li class="chapter" data-level="2.1" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html#what-is-data-science"><i class="fa fa-check"></i><b>2.1</b> What is Data Science?</a><ul>
<li class="chapter" data-level="2.1.1" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html#data"><i class="fa fa-check"></i><b>2.1.1</b> Data</a></li>
<li class="chapter" data-level="2.1.2" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html#specific-questions"><i class="fa fa-check"></i><b>2.1.2</b> Specific Questions</a></li>
<li class="chapter" data-level="2.1.3" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html#interdisciplinary-activities"><i class="fa fa-check"></i><b>2.1.3</b> Interdisciplinary Activities</a></li>
<li class="chapter" data-level="2.1.4" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html#data-centric-artifacts-and-applications"><i class="fa fa-check"></i><b>2.1.4</b> Data-centric artifacts and applications</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html#why-data-science"><i class="fa fa-check"></i><b>2.2</b> Why Data Science?</a></li>
<li class="chapter" data-level="2.3" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html#data-science-in-humanities-and-social-sciences"><i class="fa fa-check"></i><b>2.3</b> Data Science in Humanities and Social Sciences</a></li>
<li class="chapter" data-level="2.4" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html#course-organization"><i class="fa fa-check"></i><b>2.4</b> Course organization</a><ul>
<li class="chapter" data-level="2.4.1" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html#day-1-introduction-and-preparation"><i class="fa fa-check"></i><b>2.4.1</b> Day 1: Introduction and preparation</a></li>
<li class="chapter" data-level="2.4.2" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html#day-2-use-cases"><i class="fa fa-check"></i><b>2.4.2</b> Day 2: Use cases</a></li>
<li class="chapter" data-level="2.4.3" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html#day-3-presentation-and-teaching"><i class="fa fa-check"></i><b>2.4.3</b> Day 3: Presentation and teaching</a></li>
</ul></li>
<li class="chapter" data-level="2.5" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html#general-workflow"><i class="fa fa-check"></i><b>2.5</b> General Workflow</a><ul>
<li class="chapter" data-level="2.5.1" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html#defining-the-goal"><i class="fa fa-check"></i><b>2.5.1</b> Defining the goal</a></li>
<li class="chapter" data-level="2.5.2" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html#data-collection-and-management"><i class="fa fa-check"></i><b>2.5.2</b> Data collection and Management</a></li>
<li class="chapter" data-level="2.5.3" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html#modeling"><i class="fa fa-check"></i><b>2.5.3</b> Modeling</a></li>
<li class="chapter" data-level="2.5.4" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html#model-evaluation"><i class="fa fa-check"></i><b>2.5.4</b> Model evaluation</a></li>
<li class="chapter" data-level="2.5.5" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html#presentation"><i class="fa fa-check"></i><b>2.5.5</b> Presentation</a></li>
<li class="chapter" data-level="2.5.6" data-path="introduction-and-overview.html"><a href="introduction-and-overview.html#deployment"><i class="fa fa-check"></i><b>2.5.6</b> Deployment</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="an-illustrative-analysis.html"><a href="an-illustrative-analysis.html"><i class="fa fa-check"></i><b>3</b> An Illustrative Analysis</a><ul>
<li class="chapter" data-level="3.1" data-path="an-illustrative-analysis.html"><a href="an-illustrative-analysis.html#gathering-data"><i class="fa fa-check"></i><b>3.1</b> Gathering data</a><ul>
<li class="chapter" data-level="3.1.1" data-path="an-illustrative-analysis.html"><a href="an-illustrative-analysis.html#movie-ratings"><i class="fa fa-check"></i><b>3.1.1</b> Movie ratings</a></li>
<li class="chapter" data-level="3.1.2" data-path="an-illustrative-analysis.html"><a href="an-illustrative-analysis.html#movie-budgets-and-revenue"><i class="fa fa-check"></i><b>3.1.2</b> Movie budgets and revenue</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="an-illustrative-analysis.html"><a href="an-illustrative-analysis.html#manipulating-the-data"><i class="fa fa-check"></i><b>3.2</b> Manipulating the data</a></li>
<li class="chapter" data-level="3.3" data-path="an-illustrative-analysis.html"><a href="an-illustrative-analysis.html#visualizing-the-data"><i class="fa fa-check"></i><b>3.3</b> Visualizing the data</a></li>
<li class="chapter" data-level="3.4" data-path="an-illustrative-analysis.html"><a href="an-illustrative-analysis.html#modeling-data"><i class="fa fa-check"></i><b>3.4</b> Modeling data</a></li>
<li class="chapter" data-level="3.5" data-path="an-illustrative-analysis.html"><a href="an-illustrative-analysis.html#visualizing-model-result"><i class="fa fa-check"></i><b>3.5</b> Visualizing model result</a></li>
<li class="chapter" data-level="3.6" data-path="an-illustrative-analysis.html"><a href="an-illustrative-analysis.html#abstracting-the-analysis"><i class="fa fa-check"></i><b>3.6</b> Abstracting the analysis</a></li>
<li class="chapter" data-level="3.7" data-path="an-illustrative-analysis.html"><a href="an-illustrative-analysis.html#making-analyses-accessible"><i class="fa fa-check"></i><b>3.7</b> Making analyses accessible</a></li>
<li class="chapter" data-level="3.8" data-path="an-illustrative-analysis.html"><a href="an-illustrative-analysis.html#summary"><i class="fa fa-check"></i><b>3.8</b> Summary</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="setting-up-r.html"><a href="setting-up-r.html"><i class="fa fa-check"></i><b>4</b> Setting up R</a><ul>
<li class="chapter" data-level="4.1" data-path="setting-up-r.html"><a href="setting-up-r.html#setting-up-r-1"><i class="fa fa-check"></i><b>4.1</b> Setting up R</a></li>
<li class="chapter" data-level="4.2" data-path="setting-up-r.html"><a href="setting-up-r.html#setting-up-rstudio"><i class="fa fa-check"></i><b>4.2</b> Setting up Rstudio</a></li>
<li class="chapter" data-level="4.3" data-path="setting-up-r.html"><a href="setting-up-r.html#a-first-look-at-rstudio"><i class="fa fa-check"></i><b>4.3</b> A first look at Rstudio</a><ul>
<li class="chapter" data-level="4.3.1" data-path="setting-up-r.html"><a href="setting-up-r.html#interactive-console"><i class="fa fa-check"></i><b>4.3.1</b> Interactive Console</a></li>
<li class="chapter" data-level="4.3.2" data-path="setting-up-r.html"><a href="setting-up-r.html#data-viewer"><i class="fa fa-check"></i><b>4.3.2</b> Data Viewer</a></li>
<li class="chapter" data-level="4.3.3" data-path="setting-up-r.html"><a href="setting-up-r.html#names-values-and-functions"><i class="fa fa-check"></i><b>4.3.3</b> Names, values and functions</a></li>
<li class="chapter" data-level="4.3.4" data-path="setting-up-r.html"><a href="setting-up-r.html#plotting"><i class="fa fa-check"></i><b>4.3.4</b> Plotting</a></li>
<li class="chapter" data-level="4.3.5" data-path="setting-up-r.html"><a href="setting-up-r.html#editor"><i class="fa fa-check"></i><b>4.3.5</b> Editor</a></li>
<li class="chapter" data-level="4.3.6" data-path="setting-up-r.html"><a href="setting-up-r.html#files-viewer"><i class="fa fa-check"></i><b>4.3.6</b> Files viewer</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="setting-up-r.html"><a href="setting-up-r.html#r-packages"><i class="fa fa-check"></i><b>4.4</b> R packages</a></li>
<li class="chapter" data-level="4.5" data-path="setting-up-r.html"><a href="setting-up-r.html#finishing-your-setup"><i class="fa fa-check"></i><b>4.5</b> Finishing your setup</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="r-principles.html"><a href="r-principles.html"><i class="fa fa-check"></i><b>5</b> R Principles</a><ul>
<li class="chapter" data-level="5.1" data-path="r-principles.html"><a href="r-principles.html#some-history"><i class="fa fa-check"></i><b>5.1</b> Some history</a></li>
<li class="chapter" data-level="5.2" data-path="r-principles.html"><a href="r-principles.html#additional-r-resources"><i class="fa fa-check"></i><b>5.2</b> Additional R resources</a></li>
<li class="chapter" data-level="5.3" data-path="r-principles.html"><a href="r-principles.html#literate-programming"><i class="fa fa-check"></i><b>5.3</b> Literate Programming</a></li>
<li class="chapter" data-level="5.4" data-path="r-principles.html"><a href="r-principles.html#a-data-analysis-to-get-us-going"><i class="fa fa-check"></i><b>5.4</b> A data analysis to get us going</a></li>
<li class="chapter" data-level="5.5" data-path="r-principles.html"><a href="r-principles.html#getting-data"><i class="fa fa-check"></i><b>5.5</b> Getting data</a></li>
<li class="chapter" data-level="5.6" data-path="r-principles.html"><a href="r-principles.html#variables-and-value"><i class="fa fa-check"></i><b>5.6</b> Variables and Value</a></li>
<li class="chapter" data-level="5.7" data-path="r-principles.html"><a href="r-principles.html#indexing"><i class="fa fa-check"></i><b>5.7</b> Indexing</a></li>
<li class="chapter" data-level="5.8" data-path="r-principles.html"><a href="r-principles.html#exploration"><i class="fa fa-check"></i><b>5.8</b> Exploration</a></li>
<li class="chapter" data-level="5.9" data-path="r-principles.html"><a href="r-principles.html#functions"><i class="fa fa-check"></i><b>5.9</b> Functions</a></li>
<li class="chapter" data-level="5.10" data-path="r-principles.html"><a href="r-principles.html#a-note-on-data-types"><i class="fa fa-check"></i><b>5.10</b> A note on data types</a></li>
<li class="chapter" data-level="5.11" data-path="r-principles.html"><a href="r-principles.html#thinking-in-vectors"><i class="fa fa-check"></i><b>5.11</b> Thinking in vectors</a></li>
<li class="chapter" data-level="5.12" data-path="r-principles.html"><a href="r-principles.html#lists-vs.vectors"><i class="fa fa-check"></i><b>5.12</b> Lists vs. vectors</a></li>
<li class="chapter" data-level="5.13" data-path="r-principles.html"><a href="r-principles.html#making-the-process-explicit-with-pipes"><i class="fa fa-check"></i><b>5.13</b> Making the process explicit with pipes</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ingesting-data.html"><a href="ingesting-data.html"><i class="fa fa-check"></i><b>6</b> Ingesting data</a><ul>
<li class="chapter" data-level="6.1" data-path="ingesting-data.html"><a href="ingesting-data.html#structured-ingestion"><i class="fa fa-check"></i><b>6.1</b> Structured ingestion</a><ul>
<li class="chapter" data-level="6.1.1" data-path="ingesting-data.html"><a href="ingesting-data.html#csv-files-and-similar"><i class="fa fa-check"></i><b>6.1.1</b> CSV files (and similar)</a></li>
<li class="chapter" data-level="6.1.2" data-path="ingesting-data.html"><a href="ingesting-data.html#excel-spreadsheets"><i class="fa fa-check"></i><b>6.1.2</b> Excel spreadsheets</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="ingesting-data.html"><a href="ingesting-data.html#scraping"><i class="fa fa-check"></i><b>6.2</b> Scraping</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="tidying-data.html"><a href="tidying-data.html"><i class="fa fa-check"></i><b>7</b> Tidying data</a><ul>
<li class="chapter" data-level="7.1" data-path="tidying-data.html"><a href="tidying-data.html#tidy-data"><i class="fa fa-check"></i><b>7.1</b> Tidy Data</a></li>
<li class="chapter" data-level="7.2" data-path="tidying-data.html"><a href="tidying-data.html#common-problems-in-messy-data"><i class="fa fa-check"></i><b>7.2</b> Common problems in messy data</a><ul>
<li class="chapter" data-level="7.2.1" data-path="tidying-data.html"><a href="tidying-data.html#headers-as-values"><i class="fa fa-check"></i><b>7.2.1</b> Headers as values</a></li>
<li class="chapter" data-level="7.2.2" data-path="tidying-data.html"><a href="tidying-data.html#multiple-variables-in-one-column"><i class="fa fa-check"></i><b>7.2.2</b> Multiple variables in one column</a></li>
<li class="chapter" data-level="7.2.3" data-path="tidying-data.html"><a href="tidying-data.html#variables-stored-in-both-rows-and-columns"><i class="fa fa-check"></i><b>7.2.3</b> Variables stored in both rows and columns</a></li>
<li class="chapter" data-level="7.2.4" data-path="tidying-data.html"><a href="tidying-data.html#multiple-types-in-one-table"><i class="fa fa-check"></i><b>7.2.4</b> Multiple types in one table</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="tidying-data.html"><a href="tidying-data.html#data-wrangling-with-dplyr"><i class="fa fa-check"></i><b>7.3</b> Data wrangling with <code>dplyr</code></a><ul>
<li class="chapter" data-level="7.3.1" data-path="tidying-data.html"><a href="tidying-data.html#dplyr"><i class="fa fa-check"></i><b>7.3.1</b> <code>dplyr</code></a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="tidying-data.html"><a href="tidying-data.html#single-table-manipulation"><i class="fa fa-check"></i><b>7.4</b> Single-table manipulation</a><ul>
<li class="chapter" data-level="7.4.1" data-path="tidying-data.html"><a href="tidying-data.html#subsetting-observations"><i class="fa fa-check"></i><b>7.4.1</b> Subsetting Observations</a></li>
<li class="chapter" data-level="7.4.2" data-path="tidying-data.html"><a href="tidying-data.html#subsetting-variables"><i class="fa fa-check"></i><b>7.4.2</b> Subsetting Variables</a></li>
<li class="chapter" data-level="7.4.3" data-path="tidying-data.html"><a href="tidying-data.html#creating-new-variables"><i class="fa fa-check"></i><b>7.4.3</b> Creating New Variables</a></li>
<li class="chapter" data-level="7.4.4" data-path="tidying-data.html"><a href="tidying-data.html#summarizing-data"><i class="fa fa-check"></i><b>7.4.4</b> Summarizing Data</a></li>
<li class="chapter" data-level="7.4.5" data-path="tidying-data.html"><a href="tidying-data.html#grouping-data"><i class="fa fa-check"></i><b>7.4.5</b> Grouping Data</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="tidying-data.html"><a href="tidying-data.html#two-table-manipulation"><i class="fa fa-check"></i><b>7.5</b> Two-table manipulation</a><ul>
<li class="chapter" data-level="7.5.1" data-path="tidying-data.html"><a href="tidying-data.html#left-join"><i class="fa fa-check"></i><b>7.5.1</b> Left Join</a></li>
<li class="chapter" data-level="7.5.2" data-path="tidying-data.html"><a href="tidying-data.html#join-conditions"><i class="fa fa-check"></i><b>7.5.2</b> Join conditions</a></li>
<li class="chapter" data-level="7.5.3" data-path="tidying-data.html"><a href="tidying-data.html#filtering-joins"><i class="fa fa-check"></i><b>7.5.3</b> Filtering Joins</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="tidying-data.html"><a href="tidying-data.html#final-note-on-dplyr"><i class="fa fa-check"></i><b>7.6</b> Final note on <code>dplyr</code></a></li>
<li class="chapter" data-level="7.7" data-path="tidying-data.html"><a href="tidying-data.html#exercise"><i class="fa fa-check"></i><b>7.7</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="visualizing-data.html"><a href="visualizing-data.html"><i class="fa fa-check"></i><b>8</b> Visualizing data</a><ul>
<li class="chapter" data-level="8.0.1" data-path="visualizing-data.html"><a href="visualizing-data.html#eda-exploratory-data-analysis"><i class="fa fa-check"></i><b>8.0.1</b> EDA (Exploratory Data Analysis)</a></li>
<li class="chapter" data-level="8.1" data-path="visualizing-data.html"><a href="visualizing-data.html#visualization-of-single-variables"><i class="fa fa-check"></i><b>8.1</b> Visualization of single variables</a><ul>
<li class="chapter" data-level="8.1.1" data-path="visualizing-data.html"><a href="visualizing-data.html#visualization-of-pairs-of-variables"><i class="fa fa-check"></i><b>8.1.1</b> Visualization of pairs of variables</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="visualizing-data.html"><a href="visualizing-data.html#eda-with-the-grammar-of-graphics"><i class="fa fa-check"></i><b>8.2</b> EDA with the grammar of graphics</a><ul>
<li class="chapter" data-level="8.2.1" data-path="visualizing-data.html"><a href="visualizing-data.html#other-aesthetics"><i class="fa fa-check"></i><b>8.2.1</b> Other aesthetics</a></li>
<li class="chapter" data-level="8.2.2" data-path="visualizing-data.html"><a href="visualizing-data.html#faceting"><i class="fa fa-check"></i><b>8.2.2</b> Faceting</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="visualizing-data.html"><a href="visualizing-data.html#exercise-1"><i class="fa fa-check"></i><b>8.3</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="capstone-project-1.html"><a href="capstone-project-1.html"><i class="fa fa-check"></i><b>9</b> Capstone Project 1</a><ul>
<li class="chapter" data-level="9.1" data-path="capstone-project-1.html"><a href="capstone-project-1.html#project-1"><i class="fa fa-check"></i><b>9.1</b> Project 1</a></li>
<li class="chapter" data-level="9.2" data-path="capstone-project-1.html"><a href="capstone-project-1.html#project-2"><i class="fa fa-check"></i><b>9.2</b> Project 2</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html"><i class="fa fa-check"></i><b>10</b> Introduction to tidy regression analysis</a><ul>
<li class="chapter" data-level="10.1" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html#simple-regression"><i class="fa fa-check"></i><b>10.1</b> Simple Regression</a></li>
<li class="chapter" data-level="10.2" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html#inference"><i class="fa fa-check"></i><b>10.2</b> Inference</a><ul>
<li class="chapter" data-level="10.2.1" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html#confidence-interval"><i class="fa fa-check"></i><b>10.2.1</b> Confidence Interval</a></li>
<li class="chapter" data-level="10.2.2" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html#the-t-statistic-and-the-t-distribution"><i class="fa fa-check"></i><b>10.2.2</b> The <span class="math inline">\(t\)</span>-statistic and the <span class="math inline">\(t\)</span>-distribution</a></li>
<li class="chapter" data-level="10.2.3" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html#global-fit"><i class="fa fa-check"></i><b>10.2.3</b> Global Fit</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html#some-important-technicalities"><i class="fa fa-check"></i><b>10.3</b> Some important technicalities</a></li>
<li class="chapter" data-level="10.4" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html#issues-with-linear-regression"><i class="fa fa-check"></i><b>10.4</b> Issues with linear regression</a><ul>
<li class="chapter" data-level="10.4.1" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html#non-linearity-of-outcome-predictor-relationship"><i class="fa fa-check"></i><b>10.4.1</b> Non-linearity of outcome-predictor relationship</a></li>
<li class="chapter" data-level="10.4.2" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html#correlated-error"><i class="fa fa-check"></i><b>10.4.2</b> Correlated Error</a></li>
<li class="chapter" data-level="10.4.3" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html#non-constant-variance"><i class="fa fa-check"></i><b>10.4.3</b> Non-constant variance</a></li>
</ul></li>
<li class="chapter" data-level="10.5" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html#multivariate-regression"><i class="fa fa-check"></i><b>10.5</b> Multivariate Regression</a><ul>
<li class="chapter" data-level="10.5.1" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html#estimation-in-multivariate-regression"><i class="fa fa-check"></i><b>10.5.1</b> Estimation in multivariate regression</a></li>
<li class="chapter" data-level="10.5.2" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html#statistical-statements-contd"><i class="fa fa-check"></i><b>10.5.2</b> Statistical statements (cont’d)</a></li>
<li class="chapter" data-level="10.5.3" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html#the-f-test"><i class="fa fa-check"></i><b>10.5.3</b> The F-test</a></li>
<li class="chapter" data-level="10.5.4" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html#categorical-predictors-contd"><i class="fa fa-check"></i><b>10.5.4</b> Categorical predictors (cont’d)</a></li>
</ul></li>
<li class="chapter" data-level="10.6" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html#interactions-in-linear-models"><i class="fa fa-check"></i><b>10.6</b> Interactions in linear models</a></li>
<li class="chapter" data-level="10.7" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html#additional-issues-with-linear-regression"><i class="fa fa-check"></i><b>10.7</b> Additional issues with linear regression</a></li>
<li class="chapter" data-level="10.8" data-path="introduction-to-tidy-regression-analysis.html"><a href="introduction-to-tidy-regression-analysis.html#exercise-2"><i class="fa fa-check"></i><b>10.8</b> Exercise</a></li>
</ul></li>
<li class="chapter" data-level="11" data-path="text-analysis.html"><a href="text-analysis.html"><i class="fa fa-check"></i><b>11</b> Text analysis</a></li>
<li class="chapter" data-level="12" data-path="capstone-2-project.html"><a href="capstone-2-project.html"><i class="fa fa-check"></i><b>12</b> Capstone 2 Project</a></li>
<li class="chapter" data-level="13" data-path="publishing-analyses-with-r.html"><a href="publishing-analyses-with-r.html"><i class="fa fa-check"></i><b>13</b> Publishing Analyses with R</a><ul>
<li class="chapter" data-level="13.1" data-path="publishing-analyses-with-r.html"><a href="publishing-analyses-with-r.html#rmarkdown"><i class="fa fa-check"></i><b>13.1</b> RMarkdown</a></li>
<li class="chapter" data-level="13.2" data-path="publishing-analyses-with-r.html"><a href="publishing-analyses-with-r.html#shiny"><i class="fa fa-check"></i><b>13.2</b> Shiny</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="teaching-with-r.html"><a href="teaching-with-r.html"><i class="fa fa-check"></i><b>14</b> Teaching with R</a><ul>
<li class="chapter" data-level="14.1" data-path="teaching-with-r.html"><a href="teaching-with-r.html#course-materials"><i class="fa fa-check"></i><b>14.1</b> Course materials</a></li>
<li class="chapter" data-level="14.2" data-path="teaching-with-r.html"><a href="teaching-with-r.html#assignments"><i class="fa fa-check"></i><b>14.2</b> Assignments</a></li>
<li class="chapter" data-level="14.3" data-path="teaching-with-r.html"><a href="teaching-with-r.html#free-and-open-source"><i class="fa fa-check"></i><b>14.3</b> Free and open source</a></li>
<li class="chapter" data-level="14.4" data-path="teaching-with-r.html"><a href="teaching-with-r.html#wide-range-of-activities"><i class="fa fa-check"></i><b>14.4</b> Wide range of activities</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="day-3-capstone-project.html"><a href="day-3-capstone-project.html"><i class="fa fa-check"></i><b>15</b> Day 3 Capstone Project</a></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Lecture Notes: Introduction to Data Science</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="introduction-to-tidy-regression-analysis" class="section level1">
<h1><span class="header-section-number">10</span> Introduction to tidy regression analysis</h1>
<p>Linear regression is a very elegant, simple, powerful and commonly used technique for data analysis.</p>
<div id="simple-regression" class="section level2">
<h2><span class="header-section-number">10.1</span> Simple Regression</h2>
<p>Let’s start with the simplest linear model. The goal here is to analyze the relationship between a <em>continuous numerical</em> variable <span class="math inline">\(Y\)</span> and another (<em>numerical</em> or <em>categorical</em>) variable <span class="math inline">\(X\)</span>. We assume that in our population of interest the relationship between the two is given by a linear function:</p>
<p><span class="math display">\[
Y = \beta_0 + \beta_1 X
\]</span></p>
<p>Here is (simulated) data from an advertising campaign measuring sales and the amount spent in advertising. We think that sales are related to the amount of money spent on TV advertising:</p>
<p><span class="math display">\[
\mathtt{sales} \approx \beta_0 + \beta_1 \times \mathtt{TV}
\]</span></p>
<div class="figure">
<img src="img/regression_example.png" />

</div>
<p>Given this data, we would say that we <em>regress</em> <code>sales</code> on <code>TV</code> when we perform this regression analysis. As before, given data we would like to estimate what this relationship is in the <em>population</em> (what is the population in this case?). What do we need to estimate in this case? Values for <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>.</p>
<p>Let’s take a look at some data. Here is data measuring characteristics of cars, including horsepower, weight, displacement, miles per gallon. Let’s see how well a linear model captures the relationship between miles per gallon and weight</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ISLR)
<span class="kw">library</span>(dplyr)
<span class="kw">library</span>(ggplot2)
<span class="kw">library</span>(broom)

<span class="kw">data</span>(Auto)

Auto <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>weight, <span class="dt">y=</span>mpg)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">geom_smooth</span>(<span class="dt">method=</span>lm) <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">theme_minimal</span>()</code></pre></div>
<p><img src="lecture-notes_csmc320_files/figure-html/unnamed-chunk-104-1.svg" width="672" /></p>
<p>In R, linear models are built using the <code>lm</code> function</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">auto_fit &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg<span class="op">~</span>weight, <span class="dt">data=</span>Auto)
auto_fit</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ weight, data = Auto)
## 
## Coefficients:
## (Intercept)       weight  
##   46.216525    -0.007647</code></pre>
<p>This states that for this dataset <span class="math inline">\(\hat{\beta}_0 = 46.2165245\)</span> and <span class="math inline">\(\hat{\beta}_1 = -0.0076473\)</span>. What’s the interpretation? According to this model, a weightless car <code>weight=0</code> would run <span class="math inline">\(\approx 46.22\)</span> <em>miles per gallon</em> on average, and, on average, a car would run <span class="math inline">\(\approx 0.008\)</span> <em>miles per gallon</em> fewer for every extra <em>pound</em> of weight. Note, that the units of the outcome <span class="math inline">\(Y\)</span> and the predictor <span class="math inline">\(X\)</span> matter for the interpretation of these values.</p>
</div>
<div id="inference" class="section level2">
<h2><span class="header-section-number">10.2</span> Inference</h2>
<p>Now that we have an estimate, we want to know how good of an estimate this is. An important point to understand is that like the sample mean, the regression line we learn from a specific dataset is an estimate. A different sample from the same population would give us a different estimate (regression line).</p>
<p>But, statistical theory tells us that, on average, we are close to population regression line (I.e., close to <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>), that the spread around <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> is well approximated by a normal distribution and that the spread goes to zero as the sample size increases.</p>
<div class="figure">
<img src="img/population_line.png" />

</div>
<div id="confidence-interval" class="section level3">
<h3><span class="header-section-number">10.2.1</span> Confidence Interval</h3>
<p>We can construct a confidence interval to say how precise we think our estimates of the population regression line is. In particular, we want to see how precise our estimate of <span class="math inline">\(\beta_1\)</span> is, since that captures the relationship between the two variables.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">auto_fit_stats &lt;-<span class="st"> </span>auto_fit <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">tidy</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(term, estimate, std.error)
auto_fit_stats</code></pre></div>
<pre><code>##          term     estimate    std.error
## 1 (Intercept) 46.216524549 0.7986724633
## 2      weight -0.007647343 0.0002579633</code></pre>
<p>This <code>tidy</code> function is defined by the <code>broom</code> package, which is very handy to manipulate the result of learning models in a consistent manner. The <code>select</code> call removes some extra information that we will discuss shortly.</p>
<p>Given the confidence interval, we would say, “on average, a car runs <span class="math inline">\(_{-0.0082} -0.0076_{-0.0071}\)</span> <em>miles per gallon</em> fewer per pound of weight.</p>
</div>
<div id="the-t-statistic-and-the-t-distribution" class="section level3">
<h3><span class="header-section-number">10.2.2</span> The <span class="math inline">\(t\)</span>-statistic and the <span class="math inline">\(t\)</span>-distribution</h3>
<p>We can also test a null hypothesis about this relationship: “there is no relationship between weight and miles per gallon”, which translates to <span class="math inline">\(\beta_1=0\)</span>. According to the statistical theory if this hypothesis is true then the distribution of <span class="math inline">\(\hat{\beta}_1\)</span> is well approximated by <span class="math inline">\(N(0,\mathrm{se}(\hat{\beta}_1))\)</span>, and if we observe the estimated <span class="math inline">\(\hat{\beta}_1\)</span> is <em>too far</em> from 0 according to this distribution then we <em>reject</em> the hypothesis.</p>
<p>Now, there is a technicality here that is worth paying attention to. The normal approximation is good as sample size increases, but what about moderate sample sizes (say, less than 100)? The <span class="math inline">\(t\)</span> distribution provides a better approximation of the sampling distribution of these estimates for moderate sample sizes, and it tends to the normal distribution as sample size increases.</p>
<p>The <span class="math inline">\(t\)</span> distribution is commonly used in this testing situation to obtain the probability of rejecting the null hypothesis. It is based on the <span class="math inline">\(t\)</span>-statistic</p>
<p><span class="math display">\[
\frac{\hat{\beta}_1}{\mathrm{se}(\hat{\beta}_1)}
\]</span></p>
<p>You can think of this as a <em>signal-to-noise</em> ratio, or a standardizing transformation on the estimated parameter. Under the null hypothesis, it was shown that the <span class="math inline">\(t\)</span>-statistic is well approximated by a <span class="math inline">\(t\)</span>-distribution with <span class="math inline">\(n-2\)</span> <em>degrees of freedom</em> (we will get back to <em>degrees of freedom</em> shortly).</p>
<p>In our example, we get a <span class="math inline">\(t\)</span> statistic and P-value as follows:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">auto_fit_stats &lt;-<span class="st"> </span>auto_fit <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">tidy</span>()
auto_fit_stats</code></pre></div>
<pre><code>##          term     estimate    std.error statistic       p.value
## 1 (Intercept) 46.216524549 0.7986724633  57.86668 1.623069e-193
## 2      weight -0.007647343 0.0002579633 -29.64508 6.015296e-102</code></pre>
<p>We would say: “We found a statistically significant relationship between weight and miles per gallon. On average, a car runs <span class="math inline">\(_{-0.0082} -0.0076_{-0.0071}\)</span> <em>miles per gallon</em> fewer per pound of weight (<span class="math inline">\(t\)</span>=-29.65, <span class="math inline">\(p\)</span>-value &lt; <span class="math inline">\(6.02\times 10^{-102}\)</span>).”</p>
</div>
<div id="global-fit" class="section level3">
<h3><span class="header-section-number">10.2.3</span> Global Fit</h3>
<p>Now, notice that we can make <em>predictions</em> based on our regression model, and that prediction should be better than a prediction with a simple average. We can use this comparison as a measure of how good of a job we are doing using our model to fit this data: how much of the variance of <span class="math inline">\(Y\)</span> can we <em>explain</em> with our model. To do this we can calculate <em>total sum of squares</em>:</p>
<p><span class="math display">\[
TSS = \sum_i (y_i - \overline{y})^2
\]</span></p>
<p>(this is the squared error of a prediction using the sample mean of <span class="math inline">\(Y\)</span>)</p>
<p>and the <em>residual sum of squares</em>:</p>
<p><span class="math display">\[
RSS = \sum_i (y_i - \hat{y}_i)^2
\]</span></p>
<p>(which is the squared error of a prediction using the linear model we learned)</p>
<p>The commonly used <span class="math inline">\(R^2\)</span> measure comparse these two quantities:</p>
<p><span class="math display">\[
R^2 = \frac{\mathrm{TSS}-\mathrm{RSS}}{\mathrm{TSS}} = 1 - \frac{\mathrm{RSS}}{\mathrm{TSS}}
\]</span></p>
<p>These types of global statistics for the linear model can be obtained using the <code>glance</code> function in the <code>broom</code> package. In our example</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">auto_fit <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">glance</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(r.squared, sigma, statistic, df, p.value)</code></pre></div>
<pre><code>##   r.squared    sigma statistic df       p.value
## 1 0.6926304 4.332712  878.8309  2 6.015296e-102</code></pre>
<p>We will explain the the columns <code>statistic</code>, <code>df</code> and <code>p.value</code> when we discuss regression using more than a single predictor <span class="math inline">\(X\)</span>.</p>
</div>
</div>
<div id="some-important-technicalities" class="section level2">
<h2><span class="header-section-number">10.3</span> Some important technicalities</h2>
<p>We mentioned above that predictor <span class="math inline">\(X\)</span> could be <em>numeric</em> or <em>categorical</em>. However, this is not precisely true. We can use a transformation to represent <em>categorical</em> variables. Here is a simple example:</p>
<p>Suppose we have a categorical variable <code>sex</code> with values <code>female</code> and <code>male</code>, and we want to show the relationship between, say <code>credit card balance</code> and <code>sex</code>. We can create a dummy variable <span class="math inline">\(x\)</span> as follows:</p>
<p><span class="math display">\[
x_i = \left\{
\begin{aligned}
1 &amp; \textrm{ if female} \\
0 &amp; \textrm{o.w.}
\end{aligned}
\right.
\]</span></p>
<p>and fit a model <span class="math inline">\(y = \beta_0 + \beta_1 x\)</span>. What is the conditional expectation given by this model? If the person is male, then <span class="math inline">\(y=\beta_0\)</span>, if the person is female, then <span class="math inline">\(y=\beta_0 + \beta_1\)</span>. So, what is the interpretation of <span class="math inline">\(\beta_1\)</span>? The average difference in credit card balance between females and males.</p>
<p>We could do a different encoding:</p>
<p><span class="math display">\[
x_i = \left\{
\begin{aligned}
+1 &amp; \textrm{ if female} \\
-1 &amp; \textrm{o.w.}
\end{aligned}
\right.
\]</span></p>
<p>Then what is the interpretation of <span class="math inline">\(\beta_1\)</span> in this case?</p>
<p>Note, that when we call the <code>lm(y~x)</code> function and <code>x</code> is a factor with two levels, the first transformation is used by default. What if there are more than 2 levels? We need multiple regression, which we will see shortly.</p>
</div>
<div id="issues-with-linear-regression" class="section level2">
<h2><span class="header-section-number">10.4</span> Issues with linear regression</h2>
<p>There are some assumptions underlying the inferences and predictions we make using linear regression that we should verify are met when we use this framework. Let’s start with four important ones that apply to simple regression</p>
<div id="non-linearity-of-outcome-predictor-relationship" class="section level3">
<h3><span class="header-section-number">10.4.1</span> Non-linearity of outcome-predictor relationship</h3>
<p>What if the underlying relationship is not linear? We will see later that we can capture non-linear relationships between variables, but for now, let’s concentrate on detecting if a linear relationship is a good approximation. We can use exploratory visual analysis to do this for now by plotting residuals <span class="math inline">\((y_i - \hat{y}_i)^2\)</span> as a function of the fitted values <span class="math inline">\(\hat{y}_i\)</span>.</p>
<p>The <code>broom</code> package uses the <code>augment</code> function to help with this task. It augments the input data used to learn the linear model with information of the fitted model for each observation</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">augmented_auto &lt;-<span class="st"> </span>auto_fit <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">augment</span>()
augmented_auto <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>()</code></pre></div>
<pre><code>##   .rownames mpg weight  .fitted   .se.fit    .resid        .hat   .sigma
## 1         1  18   3504 19.42024 0.2575448 -1.420236 0.003533343 4.337678
## 2         2  15   3693 17.97489 0.2862653 -2.974889 0.004365337 4.335643
## 3         3  18   3436 19.94026 0.2487426 -1.940256 0.003295950 4.337158
## 4         4  16   3433 19.96320 0.2483756 -3.963198 0.003286232 4.333606
## 5         5  17   3449 19.84084 0.2503543 -2.840840 0.003338799 4.335878
## 6         6  15   4341 13.01941 0.4142337  1.980589 0.009140525 4.337104
##        .cooksd .std.resid
## 1 0.0001911753 -0.3283745
## 2 0.0010380292 -0.6881147
## 3 0.0003326721 -0.4485553
## 4 0.0013838821 -0.9162219
## 5 0.0007225022 -0.6567698
## 6 0.0009727164  0.4592282</code></pre>
<p>With that we can make the plot we need to check for possible non-linearity</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">augmented_auto <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>.fitted,<span class="dt">y=</span>.resid)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span>
<span class="st">    </span><span class="kw">geom_smooth</span>() <span class="op">+</span>
<span class="st">    </span><span class="kw">labs</span>(<span class="dt">x=</span><span class="st">&quot;fitted&quot;</span>, <span class="dt">y=</span><span class="st">&quot;residual&quot;</span>)</code></pre></div>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39;</code></pre>
<p><img src="lecture-notes_csmc320_files/figure-html/unnamed-chunk-111-1.svg" width="672" /></p>
</div>
<div id="correlated-error" class="section level3">
<h3><span class="header-section-number">10.4.2</span> Correlated Error</h3>
<p>For our inferences to be valid, we need residuals to be independent and identically distributed. We can spot non independence if we observe a trend in residuals as a function of the predictor <span class="math inline">\(X\)</span>. Here is a simulation to demonstrate this:</p>
<div class="figure">
<img src="img/correlated_error.png" />

</div>
<p>In this case, our standard error estimates would be underestimated and our confidence intervals and hypothesis testing results would be biased.</p>
</div>
<div id="non-constant-variance" class="section level3">
<h3><span class="header-section-number">10.4.3</span> Non-constant variance</h3>
<p>Another violation of the iid assumption would be observed if the spread of residuals is not independent of the fitted values. Here is an illustration, and a possible fix using a log transformation on the outcome <span class="math inline">\(Y\)</span>.</p>
<div class="figure">
<img src="img/residual_variance.png" />

</div>
</div>
</div>
<div id="multivariate-regression" class="section level2">
<h2><span class="header-section-number">10.5</span> Multivariate Regression</h2>
<p>Now that we’ve seen regression using a single predictor we’ll move on to regression using multiple predictors. In this case, we use models of conditional expectation represented as linear functions of multiple variables.</p>
<p>In the case of our advertising example, this would be a model:</p>
<p><span class="math display">\[
\mathtt{sales} = \beta_0 + \beta_1 \times \mathtt{TV} + \beta_2 \times \mathtt{newspaper} + \beta_3 \times \mathtt{facebook}
\]</span></p>
<p>These models let us make statements of the type: “holding everything else constant, sales increased on average by 1000 per dollar spent on Facebook advertising” (this would be given by parameter <span class="math inline">\(\beta_3\)</span> in the example model).</p>
<div id="estimation-in-multivariate-regression" class="section level3">
<h3><span class="header-section-number">10.5.1</span> Estimation in multivariate regression</h3>
<p>Continuing with our Auto example, we can build a model for miles per gallon using multiple predictors:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">auto_fit &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg<span class="op">~</span><span class="dv">1</span><span class="op">+</span>weight<span class="op">+</span>cylinders<span class="op">+</span>horsepower<span class="op">+</span>displacement<span class="op">+</span>year, <span class="dt">data=</span>Auto)
auto_fit</code></pre></div>
<pre><code>## 
## Call:
## lm(formula = mpg ~ 1 + weight + cylinders + horsepower + displacement + 
##     year, data = Auto)
## 
## Coefficients:
##  (Intercept)        weight     cylinders    horsepower  displacement  
##   -12.779493     -0.006524     -0.343690     -0.007715      0.006996  
##         year  
##     0.749924</code></pre>
<p>From this model we can make the statement: “Holding everything else constant, cars run 0.76 miles per gallon more each year on average”.</p>
</div>
<div id="statistical-statements-contd" class="section level3">
<h3><span class="header-section-number">10.5.2</span> Statistical statements (cont’d)</h3>
<p>Like simple linear regression, we can construct confidence intervals, and test a null hypothesis of no relationship (<span class="math inline">\(\beta_j=0\)</span>) for the parameter corresponding to each predictor. This is again nicely managed by the <code>broom</code> package:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">auto_fit_stats &lt;-<span class="st"> </span>auto_fit <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">tidy</span>()
auto_fit_stats <span class="op">%&gt;%</span><span class="st"> </span>knitr<span class="op">::</span><span class="kw">kable</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">-12.7794934</td>
<td align="right">4.2739387</td>
<td align="right">-2.9900975</td>
<td align="right">0.0029676</td>
</tr>
<tr class="even">
<td align="left">weight</td>
<td align="right">-0.0065245</td>
<td align="right">0.0005866</td>
<td align="right">-11.1215621</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">cylinders</td>
<td align="right">-0.3436900</td>
<td align="right">0.3315619</td>
<td align="right">-1.0365786</td>
<td align="right">0.3005812</td>
</tr>
<tr class="even">
<td align="left">horsepower</td>
<td align="right">-0.0077149</td>
<td align="right">0.0107036</td>
<td align="right">-0.7207702</td>
<td align="right">0.4714872</td>
</tr>
<tr class="odd">
<td align="left">displacement</td>
<td align="right">0.0069964</td>
<td align="right">0.0073095</td>
<td align="right">0.9571736</td>
<td align="right">0.3390787</td>
</tr>
<tr class="even">
<td align="left">year</td>
<td align="right">0.7499243</td>
<td align="right">0.0524361</td>
<td align="right">14.3016700</td>
<td align="right">0.0000000</td>
</tr>
</tbody>
</table>
<p>In this case we would reject the null hypothesis of no relationship only for predictors <code>weight</code> and <code>year</code>. We would write the statement for year as follows:</p>
<p>“Holding everything else constant, cars run <span class="math inline">\({}_{0.65} 0.75_{0.85}\)</span> miles per gallon more each year on average (P-value<span class="math inline">\(&lt;1e-16\)</span>)”.</p>
</div>
<div id="the-f-test" class="section level3">
<h3><span class="header-section-number">10.5.3</span> The F-test</h3>
<p>We can make additional statements for multivariate regression: “is there a relationship between <em>any</em> of the predictors and the response?”. Mathematically, we write this as <span class="math inline">\(\beta_1 = \beta_2 = \cdots = \beta_p = 0\)</span>.</p>
<p>Under the null, our model for <span class="math inline">\(y\)</span> would be estimated by the sample mean <span class="math inline">\(\overline{y}\)</span>, and the error for that estimate is by total sum of squared error <span class="math inline">\(TSS\)</span>. As before, we can compare this to the residual sum of squared error <span class="math inline">\(RSS\)</span> using the <span class="math inline">\(F\)</span> statistic:</p>
<p><span class="math display">\[
\frac{(\mathrm{TSS}-\mathrm{RSS})/p}{\mathrm{RSS}/(n-p-1)}
\]</span></p>
<p>If this statistic is greater (enough) than 1, then we reject hypothesis that there is no relationship between response and predictors.</p>
<p>Back to our example, we use the <code>glance</code> function to compute this type of summary:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">auto_fit <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">glance</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">select</span>(r.squared, sigma, statistic, df, p.value) <span class="op">%&gt;%</span>
<span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">df</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.8089093</td>
<td align="right">3.433902</td>
<td align="right">326.7965</td>
<td align="right">6</td>
<td align="right">0</td>
</tr>
</tbody>
</table>
<p>In comparison with the linear model only using <code>weight</code>, this multivariate model explains <em>more of the variance</em> of <code>mpg</code>, but using more predictors. This is where the notion of <em>degrees of freedom</em> comes in: we now have a model with expanded <em>representational</em> ability.</p>
<p>However, the bigger the model, we are conditioning more and more, and intuitively, given a fixed dataset, have fewer data points to estimate conditional expectation for each value of the predictors. That means, that are estimated conditional expectation is less <em>precise</em>.</p>
<p>To capture this phenomenon, we want statistics that tradeoff how well the model fits the data, and the “complexity” of the model. Now, we can look at the full output of the <code>glance</code> function:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">auto_fit <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">glance</span>() <span class="op">%&gt;%</span>
<span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
<th align="right">logLik</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">deviance</th>
<th align="right">df.residual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.8089093</td>
<td align="right">0.806434</td>
<td align="right">3.433902</td>
<td align="right">326.7965</td>
<td align="right">0</td>
<td align="right">6</td>
<td align="right">-1036.81</td>
<td align="right">2087.62</td>
<td align="right">2115.419</td>
<td align="right">4551.589</td>
<td align="right">386</td>
</tr>
</tbody>
</table>
<p>Columns <code>AIC</code> and <code>BIC</code> display statistics that penalize model fit with model size. The smaller this value, the better. Let’s now compare a model only using <code>weight</code>, a model only using <code>weight</code> and <code>year</code> and the full multiple regression model we saw before.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lm</span>(mpg<span class="op">~</span>weight, <span class="dt">data=</span>Auto) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">glance</span>() <span class="op">%&gt;%</span>
<span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
<th align="right">logLik</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">deviance</th>
<th align="right">df.residual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.6926304</td>
<td align="right">0.6918423</td>
<td align="right">4.332712</td>
<td align="right">878.8309</td>
<td align="right">0</td>
<td align="right">2</td>
<td align="right">-1129.969</td>
<td align="right">2265.939</td>
<td align="right">2277.852</td>
<td align="right">7321.234</td>
<td align="right">390</td>
</tr>
</tbody>
</table>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">lm</span>(mpg<span class="op">~</span>weight<span class="op">+</span>year, <span class="dt">data=</span>Auto) <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">glance</span>() <span class="op">%&gt;%</span>
<span class="st">  </span>knitr<span class="op">::</span><span class="kw">kable</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="right">r.squared</th>
<th align="right">adj.r.squared</th>
<th align="right">sigma</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
<th align="right">df</th>
<th align="right">logLik</th>
<th align="right">AIC</th>
<th align="right">BIC</th>
<th align="right">deviance</th>
<th align="right">df.residual</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">0.8081803</td>
<td align="right">0.8071941</td>
<td align="right">3.427153</td>
<td align="right">819.473</td>
<td align="right">0</td>
<td align="right">3</td>
<td align="right">-1037.556</td>
<td align="right">2083.113</td>
<td align="right">2098.998</td>
<td align="right">4568.952</td>
<td align="right">389</td>
</tr>
</tbody>
</table>
<p>In this case, using more predictors beyond <code>weight</code> and <code>year</code> doesn’t help.</p>
</div>
<div id="categorical-predictors-contd" class="section level3">
<h3><span class="header-section-number">10.5.4</span> Categorical predictors (cont’d)</h3>
<p>We saw transformations for categorical predictors with only two values, and deferred our discussion of categorical predictors with more than two values. In our example we have the <code>origin</code> predictor, corresponding to where the car was manufactured, which has multiple values</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Auto &lt;-<span class="st"> </span>Auto <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">origin=</span><span class="kw">factor</span>(origin))
<span class="kw">levels</span>(Auto<span class="op">$</span>origin)</code></pre></div>
<pre><code>## [1] &quot;1&quot; &quot;2&quot; &quot;3&quot;</code></pre>
<p>As before, we can only use numerical predictors in linear regression models. The most common way of doing this is to create new dummy predictors to <em>encode</em> the value of the categorical predictor. Let’s take a categorical variable <code>major</code> that can take values <code>CS</code>, <code>MATH</code>, <code>BUS</code>. We can encode these values using variables <span class="math inline">\(x_1\)</span> and <span class="math inline">\(x_2\)</span></p>
<p><span class="math display">\[
x_1 = \left\{
\begin{aligned}
1 &amp; \textrm{ if MATH} \\
0 &amp; \textrm{ o.w.}
\end{aligned}
\right.
\]</span></p>
<p><span class="math display">\[
x_2 = \left\{
\begin{aligned}
1 &amp; \textrm{ if BUS} \\
0 &amp; \textrm{ o.w.}
\end{aligned}
\right.
\]</span></p>
<p>Now let’s build a model to capture the relationship between <code>salary</code> and <code>major</code>:</p>
<p><span class="math display">\[
\mathtt{salary} = \beta_0 + \beta_1 x_1 + \beta_2 x_2
\]</span></p>
<p>What is the expected salary for a CS major? <span class="math inline">\(\beta_0\)</span>.<br />
For a MATH major? <span class="math inline">\(\beta_0 + \beta_1\)</span>. For a BUS major? <span class="math inline">\(\beta_0 + \beta_2\)</span>.</p>
<p>So, <span class="math inline">\(\beta_1\)</span> is the average difference in salary between MATH and CS majors. How can we calculate the average difference in salary between MATH and BUS majors? <span class="math inline">\(\beta_1 - \beta_2\)</span>.</p>
<p>The <code>lm</code> function in R does this transformation by default when a variable has class <code>factor</code>. We can see what the underlying numerical predictors look like by using the <code>model_matrix</code> function and passing it the model formula we build:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">extended_df &lt;-<span class="st"> </span><span class="kw">model.matrix</span>(<span class="op">~</span><span class="kw">factor</span>(origin), <span class="dt">data=</span>Auto) <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">as.data.frame</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">mutate</span>(<span class="dt">origin =</span> <span class="kw">factor</span>(Auto<span class="op">$</span>origin))</code></pre></div>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">extended_df <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(origin <span class="op">==</span><span class="st"> &quot;1&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>()</code></pre></div>
<pre><code>##   (Intercept) factor(origin)2 factor(origin)3 origin
## 1           1               0               0      1
## 2           1               0               0      1
## 3           1               0               0      1
## 4           1               0               0      1
## 5           1               0               0      1
## 6           1               0               0      1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">extended_df <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">filter</span>(origin <span class="op">==</span><span class="st"> &quot;2&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>()</code></pre></div>
<pre><code>##   (Intercept) factor(origin)2 factor(origin)3 origin
## 1           1               1               0      2
## 2           1               1               0      2
## 3           1               1               0      2
## 4           1               1               0      2
## 5           1               1               0      2
## 6           1               1               0      2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">extended_df <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">filter</span>(origin <span class="op">==</span><span class="st"> &quot;3&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>()</code></pre></div>
<pre><code>##   (Intercept) factor(origin)2 factor(origin)3 origin
## 1           1               0               1      3
## 2           1               0               1      3
## 3           1               0               1      3
## 4           1               0               1      3
## 5           1               0               1      3
## 6           1               0               1      3</code></pre>
</div>
</div>
<div id="interactions-in-linear-models" class="section level2">
<h2><span class="header-section-number">10.6</span> Interactions in linear models</h2>
<p>The linear models so far include <em>additive</em> terms for a single predictor. That let us made statemnts of the type “holding everything else constant…”. But what if we think that a pair of predictors <em>together</em> have a relationship with the outcome. We can add these <em>interaction</em> terms to our linear models as products:</p>
<p>Consider the advertising example:</p>
<p><span class="math display">\[
  \mathtt{sales} = \beta_0 + \beta_1 \times \mathtt{TV} + \beta_2 \times \mathtt{facebook} + \beta_3 \times (\mathtt{TV} \times \mathtt{facebook})
\]</span></p>
<p>If <span class="math inline">\(\beta_3\)</span> is positive, then the effect of increasing TV advertising money is increased if facebook advertising is also increased.</p>
<p>When using categorical variables, interactions have an elegant interpretation. Consider our car example, and suppose we build a model with an interaction between <code>weight</code> and <code>origin</code>. Let’s look at what the numerical predictors look like:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Auto<span class="op">$</span>origin &lt;-<span class="st"> </span><span class="kw">factor</span>(Auto<span class="op">$</span>origin)
extended_df &lt;-<span class="st"> </span><span class="kw">model.matrix</span>(<span class="op">~</span>weight<span class="op">+</span>origin<span class="op">+</span>weight<span class="op">:</span>origin, <span class="dt">data=</span>Auto) <span class="op">%&gt;%</span>
<span class="kw">as.data.frame</span>() <span class="op">%&gt;%</span>
<span class="kw">mutate</span>(<span class="dt">origin =</span> <span class="kw">factor</span>(Auto<span class="op">$</span>origin))

extended_df <span class="op">%&gt;%</span>
<span class="kw">filter</span>(origin <span class="op">==</span><span class="st"> &quot;1&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>()</code></pre></div>
<pre><code>##   (Intercept) weight origin2 origin3 weight:origin2 weight:origin3 origin
## 1           1   3504       0       0              0              0      1
## 2           1   3693       0       0              0              0      1
## 3           1   3436       0       0              0              0      1
## 4           1   3433       0       0              0              0      1
## 5           1   3449       0       0              0              0      1
## 6           1   4341       0       0              0              0      1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">extended_df <span class="op">%&gt;%</span>
<span class="kw">filter</span>(origin <span class="op">==</span><span class="st"> &quot;2&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>()</code></pre></div>
<pre><code>##   (Intercept) weight origin2 origin3 weight:origin2 weight:origin3 origin
## 1           1   1835       1       0           1835              0      2
## 2           1   2672       1       0           2672              0      2
## 3           1   2430       1       0           2430              0      2
## 4           1   2375       1       0           2375              0      2
## 5           1   2234       1       0           2234              0      2
## 6           1   2123       1       0           2123              0      2</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">extended_df <span class="op">%&gt;%</span>
<span class="kw">filter</span>(origin <span class="op">==</span><span class="st"> &quot;3&quot;</span>) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">head</span>()</code></pre></div>
<pre><code>##   (Intercept) weight origin2 origin3 weight:origin2 weight:origin3 origin
## 1           1   2372       0       1              0           2372      3
## 2           1   2130       0       1              0           2130      3
## 3           1   2130       0       1              0           2130      3
## 4           1   2228       0       1              0           2228      3
## 5           1   1773       0       1              0           1773      3
## 6           1   1613       0       1              0           1613      3</code></pre>
<p>So what is the expected miles per gallon for a car with <code>origin == 1</code> as a function of weight?</p>
<p><span class="math display">\[
\mathtt{mpg} = \beta_0 + \beta_1 \times \mathtt{weight}
\]</span></p>
<p>Now how about a car with <code>origin == 2</code>?</p>
<p><span class="math display">\[
\mathtt{mpg} = \beta_0 + \beta_1 \times \mathtt{weight} + \beta_2 + \beta_4 \times \mathtt{weight}
\]</span></p>
<p>Now think of the graphical representation of these lines. For <code>origin == 1</code> the intercept of the regression line is <span class="math inline">\(\beta_0\)</span> and its slope is <span class="math inline">\(\beta_1\)</span>. For <code>origin == 2</code> the intercept of the regression line is <span class="math inline">\(\beta_0 + \beta_2\)</span> and its slope is <span class="math inline">\(\beta_1+\beta_4\)</span>.</p>
<p><code>ggplot</code> does this when we map a factor variable to a aesthetic, say color, and use the <code>geom_smooth</code> method:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Auto <span class="op">%&gt;%</span>
<span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>weight, <span class="dt">y=</span>mpg, <span class="dt">color=</span>origin)) <span class="op">+</span>
<span class="kw">geom_point</span>() <span class="op">+</span>
<span class="kw">geom_smooth</span>(<span class="dt">method=</span>lm)</code></pre></div>
<p><img src="lecture-notes_csmc320_files/figure-html/unnamed-chunk-128-1.svg" width="672" /></p>
<p>The intercept of the three lines seem to be different, but the slope of <code>origin == 3</code> looks different (decreases faster) than the slopes of <code>origin == 1</code> and <code>origin == 2</code> that look very similar to each other.</p>
<p>Let’s fit the model and see how much statistical confidence we can give to those observations:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">auto_fit &lt;-<span class="st"> </span><span class="kw">lm</span>(mpg<span class="op">~</span>weight<span class="op">*</span>origin, <span class="dt">data=</span>Auto)
auto_fit_stats &lt;-<span class="st"> </span>auto_fit <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">tidy</span>() 
auto_fit_stats <span class="op">%&gt;%</span><span class="st"> </span>knitr<span class="op">::</span><span class="kw">kable</span>()</code></pre></div>
<table>
<thead>
<tr class="header">
<th align="left">term</th>
<th align="right">estimate</th>
<th align="right">std.error</th>
<th align="right">statistic</th>
<th align="right">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">(Intercept)</td>
<td align="right">43.1484685</td>
<td align="right">1.1861118</td>
<td align="right">36.3780794</td>
<td align="right">0.0000000</td>
</tr>
<tr class="even">
<td align="left">weight</td>
<td align="right">-0.0068540</td>
<td align="right">0.0003423</td>
<td align="right">-20.0204971</td>
<td align="right">0.0000000</td>
</tr>
<tr class="odd">
<td align="left">origin2</td>
<td align="right">1.1247469</td>
<td align="right">2.8780381</td>
<td align="right">0.3908033</td>
<td align="right">0.6961582</td>
</tr>
<tr class="even">
<td align="left">origin3</td>
<td align="right">11.1116815</td>
<td align="right">3.5743225</td>
<td align="right">3.1087518</td>
<td align="right">0.0020181</td>
</tr>
<tr class="odd">
<td align="left">weight:origin2</td>
<td align="right">0.0000036</td>
<td align="right">0.0011106</td>
<td align="right">0.0032191</td>
<td align="right">0.9974332</td>
</tr>
<tr class="even">
<td align="left">weight:origin3</td>
<td align="right">-0.0038651</td>
<td align="right">0.0015411</td>
<td align="right">-2.5079723</td>
<td align="right">0.0125521</td>
</tr>
</tbody>
</table>
<p>So we can say that for <code>origin == 3</code> the relationship between <code>mpg</code> and <code>weight</code> is different but not for the other two values of <code>origin</code>. Now, there is still an issue here because this could be the result of a poor fit from a linear model, it seems none of these lines do a very good job of modeling the data we have. We can again check this for this model:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">auto_fit <span class="op">%&gt;%</span><span class="st"> </span>
<span class="st">  </span><span class="kw">augment</span>() <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span>.fitted, <span class="dt">y=</span>.resid)) <span class="op">+</span>
<span class="st">  </span><span class="kw">geom_point</span>()</code></pre></div>
<p><img src="lecture-notes_csmc320_files/figure-html/unnamed-chunk-130-1.svg" width="672" /></p>
<p>The fact that residuals are not centered around zero suggests that a linear fit does not work well in this case.</p>
</div>
<div id="additional-issues-with-linear-regression" class="section level2">
<h2><span class="header-section-number">10.7</span> Additional issues with linear regression</h2>
<p>We saw previously some issues with linear regression that we should take into account when using this method for modeling. Multiple linear regression introduces an additional issue that is extremely important to consider when interpreting the results of these analyses: collinearity.</p>
<div class="figure">
<img src="img/collinearity.png" />

</div>
<p>In this example, you have two predictors that are very closely related. In that case, the set of <span class="math inline">\(\beta\)</span>’s that minimize RSS may not be unique, and therefore our interpretation is invalid. You can identify this potential problem by regressing predictors onto each other. The usual solution is to fit models only including one of the colinear variables.</p>
</div>
<div id="exercise-2" class="section level2">
<h2><span class="header-section-number">10.8</span> Exercise</h2>
<p>Here you will practice and experiment with linear regression using data from <a href="http://gapminder.org">gapminder.org</a>. I recommend spending a little time looking at material there, it is quite an informative site.</p>
<p>We will use a subset of data provided by gapminder provided by <a href="http://www.stat.ubc.ca/~jenny/">Jennifer Bryan</a> described in it’s <a href="https://github.com/jennybc/gapminder">github page</a>.</p>
<p>The following commands load the dataset</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(gapminder)
<span class="kw">data</span>(gapminder)</code></pre></div>
<p>For this exercise you will explore how life expectancy has changed over 50 years across the world, and how economic measures like gross domestic product (GDP) are related to it.</p>
<p><strong>Exercise 1</strong>: <em>Make a scatter plot of life expectancy across time.</em></p>
<p><strong>Question 1</strong>: <em>Is there a general trend (e.g., increasing or decreasing) for life expectancy across time? Is this trend linear? (answering this qualitatively from the plot, you will do a statistical analysis of this question shortly)</em></p>
<p>A slightly different way of making the same plot is looking at the distribution of life expectancy across countries as it changes over time:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(dplyr)
<span class="kw">library</span>(ggplot2)

gapminder <span class="op">%&gt;%</span>
<span class="st">  </span><span class="kw">ggplot</span>(<span class="kw">aes</span>(<span class="dt">x=</span><span class="kw">factor</span>(year), <span class="dt">y=</span>lifeExp)) <span class="op">+</span>
<span class="st">    </span><span class="kw">geom_violin</span>() <span class="op">+</span>
<span class="st">    </span><span class="kw">labs</span>(<span class="dt">title=</span><span class="st">&quot;Life expectancy over time&quot;</span>,
         <span class="dt">x =</span> <span class="st">&quot;year&quot;</span>,
         <span class="dt">y =</span> <span class="st">&quot;life expectancy&quot;</span>)</code></pre></div>
<p><img src="lecture-notes_csmc320_files/figure-html/unnamed-chunk-132-1.svg" width="1152" /></p>
<p>This type of plot is called a <em>violin plot</em>, and it displays the distribution of the variable in the y-axis for each value of the variable in the x-axis.</p>
<p><strong>Question 2</strong>: <em>How would you describe the distribution of life expectancy across countries for individual years? Is it skewed, or not? Unimodal or not? Symmetric around it’s center?</em></p>
<p>Based on this plot, consider the following questions.</p>
<p><strong>Question 3</strong>: <em>Suppose I fit a linear regression model of life expectancy vs. year (treating it as a continuous variable), and test for a relationship between year and life expectancy, will you reject the null hypothesis of no relationship? (do this without fitting the model yet. I am testing your intuition.)</em></p>
<p><strong>Question 4</strong>: <em>What would a violin plot of residuals from the linear model in Question 3 vs. year look like? (Again, don’t do the analysis yet, answer this intuitively)</em></p>
<p><strong>Question 5</strong>: <em>According to the assumptions of the linear regression model, what <strong>should</strong> that violin plot look like?</em></p>
<p><strong>Exercise 2</strong>: <em>Fit a linear regression model using the <code>lm</code> function for life expectancy vs. year (as a continuous variable). Use the <code>broom::tidy</code> to look at the resulting model.</em></p>
<p><strong>Question 6</strong>: <em>On average, by how much does life expectancy increase every year around the world?</em></p>
<p><strong>Question 7</strong>: <em>Do you reject the null hypothesis of no relationship between year and life expectancy? Why?</em></p>
<p><strong>Exercise 3</strong>: <em>Make a violin plot of residuals vs. year for the linear model from Exercise 2 (use the <code>broom::augment</code> function).</em></p>
<p><strong>Question 8</strong>: <em>Does the plot of Excersize 3 match your expectations (as you answered Question 4)?</em></p>
<p><strong>Exercise 4</strong>: <em>Make a boxplot (or violin plot) of model residuals vs. continent.</em></p>
<p><strong>Question 9</strong>: <em>Is there a dependence between model residual and continent? If so, what would that suggest when performing a regression analysis of life expectancy across time?</em></p>
<p><strong>Exercise 5</strong>: <em>Use <code>geom_smooth(method=lm)</code> in ggplot as part of a scatter plot of life expectancy vs. year, grouped by continent (e.g., using the <code>color</code> aesthetic mapping).</em></p>
<p><strong>Question 10</strong>: <em>Based on this plot, should your regression model include an interaction term for continent <strong>and</strong> year? Why?</em></p>
<p><strong>Exercise 6</strong>: <em>Fit a linear regression model for life expectancy including a term for an interaction between continent and year. Use the <code>broom::tidy</code> function to show the resulting model.</em></p>
<p><strong>Question 11</strong>: <em>Are all parameters in the model significantly different from zero? If not, which are not significantly different from zero?</em></p>
<p><strong>Question 12</strong>: <em>On average, by how much does life expectancy increase each year for each continent? (Provide code to answer this question by extracting relevant estimates from model fit)</em></p>
<p><strong>Exercise 7</strong>: <em>Use the <code>anova</code> function to perform an F-test that compares how well two models fit your data: (a) the linear regression models from Exercise 2 (only including year as a covariate) and (b) Exercise 6 (including interaction between year and continent).</em></p>
<p><strong>Question 13</strong>: <em>Is the interaction model significantly better than the year-only model? Why?</em></p>
<p><strong>Exercise 8</strong>: <em>Make a residuals vs. year violin plot for the interaction model. Comment on how well it matches assumptions of the linear regression model. Do the same for a residuals vs. fitted values model.</em> (You should use the <code>broom::augment</code> function).</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="capstone-project-1.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="text-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["lecture-notes_csmc320.pdf"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
